# Looker API 3.0 Reference
# 
# ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
# 
# OpenAPI spec version: 3.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DashboardLayout Class
#'
#' @field id 
#' @field dashboard_id 
#' @field type 
#' @field active 
#' @field column_width 
#' @field width 
#' @field deleted 
#' @field dashboard_layout_components 
#' @field can 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DashboardLayout <- R6::R6Class(
  'DashboardLayout',
  public = list(
    `id` = NULL,
    `dashboard_id` = NULL,
    `type` = NULL,
    `active` = NULL,
    `column_width` = NULL,
    `width` = NULL,
    `deleted` = NULL,
    `dashboard_layout_components` = NULL,
    `can` = NULL,
    initialize = function(`id`, `dashboard_id`, `type`, `active`, `column_width`, `width`, `deleted`, `dashboard_layout_components`, `can`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`dashboard_id`)) {
        stopifnot(is.character(`dashboard_id`), length(`dashboard_id`) == 1)
        self$`dashboard_id` <- `dashboard_id`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`active`)) {
        self$`active` <- `active`
      }
      if (!missing(`column_width`)) {
        stopifnot(is.numeric(`column_width`), length(`column_width`) == 1)
        self$`column_width` <- `column_width`
      }
      if (!missing(`width`)) {
        stopifnot(is.numeric(`width`), length(`width`) == 1)
        self$`width` <- `width`
      }
      if (!missing(`deleted`)) {
        self$`deleted` <- `deleted`
      }
      if (!missing(`dashboard_layout_components`)) {
        stopifnot(is.list(`dashboard_layout_components`), length(`dashboard_layout_components`) != 0)
        lapply(`dashboard_layout_components`, function(x) stopifnot(R6::is.R6(x)))
        self$`dashboard_layout_components` <- `dashboard_layout_components`
      }
      if (!missing(`can`)) {
        self$`can` <- `can`
      }
    },
    toJSON = function() {
      DashboardLayoutObject <- list()
      if (!is.null(self$`id`)) {
        DashboardLayoutObject[['id']] <- self$`id`
      }
      if (!is.null(self$`dashboard_id`)) {
        DashboardLayoutObject[['dashboard_id']] <- self$`dashboard_id`
      }
      if (!is.null(self$`type`)) {
        DashboardLayoutObject[['type']] <- self$`type`
      }
      if (!is.null(self$`active`)) {
        DashboardLayoutObject[['active']] <- self$`active`
      }
      if (!is.null(self$`column_width`)) {
        DashboardLayoutObject[['column_width']] <- self$`column_width`
      }
      if (!is.null(self$`width`)) {
        DashboardLayoutObject[['width']] <- self$`width`
      }
      if (!is.null(self$`deleted`)) {
        DashboardLayoutObject[['deleted']] <- self$`deleted`
      }
      if (!is.null(self$`dashboard_layout_components`)) {
        DashboardLayoutObject[['dashboard_layout_components']] <- lapply(self$`dashboard_layout_components`, function(x) x$toJSON())
      }
      if (!is.null(self$`can`)) {
        DashboardLayoutObject[['can']] <- self$`can`
      }

      DashboardLayoutObject
    },
    fromJSON = function(DashboardLayoutJson) {
      DashboardLayoutObject <- jsonlite::fromJSON(DashboardLayoutJson)
      if (!is.null(DashboardLayoutObject$`id`)) {
        self$`id` <- DashboardLayoutObject$`id`
      }
      if (!is.null(DashboardLayoutObject$`dashboard_id`)) {
        self$`dashboard_id` <- DashboardLayoutObject$`dashboard_id`
      }
      if (!is.null(DashboardLayoutObject$`type`)) {
        self$`type` <- DashboardLayoutObject$`type`
      }
      if (!is.null(DashboardLayoutObject$`active`)) {
        self$`active` <- DashboardLayoutObject$`active`
      }
      if (!is.null(DashboardLayoutObject$`column_width`)) {
        self$`column_width` <- DashboardLayoutObject$`column_width`
      }
      if (!is.null(DashboardLayoutObject$`width`)) {
        self$`width` <- DashboardLayoutObject$`width`
      }
      if (!is.null(DashboardLayoutObject$`deleted`)) {
        self$`deleted` <- DashboardLayoutObject$`deleted`
      }
      if (!is.null(DashboardLayoutObject$`dashboard_layout_components`)) {
        self$`dashboard_layout_components` <- lapply(DashboardLayoutObject$`dashboard_layout_components`, function(x) {
          dashboard_layout_componentsObject <- DashboardLayoutComponent$new()
          dashboard_layout_componentsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          dashboard_layout_componentsObject
        })
      }
      if (!is.null(DashboardLayoutObject$`can`)) {
        self$`can` <- DashboardLayoutObject$`can`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "dashboard_id": %s,
           "type": %s,
           "active": %s,
           "column_width": %d,
           "width": %d,
           "deleted": %s,
           "dashboard_layout_components": [%s],
           "can": %s
        }',
        self$`id`,
        self$`dashboard_id`,
        self$`type`,
        self$`active`,
        self$`column_width`,
        self$`width`,
        self$`deleted`,
        lapply(self$`dashboard_layout_components`, function(x) paste(x$toJSON(), sep=",")),
        self$`can`
      )
    },
    fromJSONString = function(DashboardLayoutJson) {
      DashboardLayoutObject <- jsonlite::fromJSON(DashboardLayoutJson)
      self$`id` <- DashboardLayoutObject$`id`
      self$`dashboard_id` <- DashboardLayoutObject$`dashboard_id`
      self$`type` <- DashboardLayoutObject$`type`
      self$`active` <- DashboardLayoutObject$`active`
      self$`column_width` <- DashboardLayoutObject$`column_width`
      self$`width` <- DashboardLayoutObject$`width`
      self$`deleted` <- DashboardLayoutObject$`deleted`
      self$`dashboard_layout_components` <- lapply(DashboardLayoutObject$`dashboard_layout_components`, function(x) DashboardLayoutComponent$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`can` <- DashboardLayoutObject$`can`
    }
  )
)
